USE `pas`;

DROP TABLE IF EXISTS `pet`;

CREATE TABLE `pas`.`pet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `age` INT NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `sex` VARCHAR(64) NOT NULL,
  `price` DOUBLE NOT NULL,
  `profile` VARCHAR(300) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));