USE `pas`;

DROP TABLE IF EXISTS `adoption_prop`;

CREATE TABLE `pas`.`adoption_prop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adoption_id` INT NOT NULL,
  `prop_id` INT NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));